import = [
    "~/.config/alacritty/themes/themes/nord.toml"
]

[font]
size = 13.0

[font.normal]
# family = "D2CodingLigature Nerd Font Mono"
family = "IosevkaTerm Nerd Font Mono"
# family = "ZedMono Nerd Font Mono"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5C"
key = "Right"
mods = "Alt|Shift"

[window]
option_as_alt = "Both"

[shell]
program = "/usr/bin/fish"
args = ["--login"]
