# import = [
#     "~/.config/alacritty/alacritty-theme/themes/zenburn.toml"
# ]

# Zenwritten theme:
# https://github.com/zenbones-theme/zenbones.nvim/blob/main/extras/alacritty/zenwritten_dark.toml
[colors.bright]
black = "#3D3839"
red = "#E8838F"
green = "#8BAE68"
yellow = "#D68C67"
blue = "#61ABDA"
magenta = "#CF86C1"
cyan = "#65B8C1"
white = "#8E8E8E"
[colors.cursor]
cursor = "#C9C9C9"
text = "#191919"
[colors.normal]
black = "#191919"
blue = "#6099C0"
cyan = "#66A5AD"
green = "#819B69"
magenta = "#B279A7"
red = "#DE6E7C"
white = "#BBBBBB"
yellow = "#B77E64"
[colors.primary]
background = "#191919"
foreground = "#BBBBBB"

[font]
size = 13.0

[font.normal]
# family = "D2CodingLigature Nerd Font Mono"
family = "Iosevka Nerd Font Mono"
# family = "ZedMono Nerd Font Mono"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5C"
key = "Right"
mods = "Alt|Shift"

[window]
option_as_alt = "Both"
